### PR TITLE
New Project Structure

### PR DESCRIPTION
**Pull request by sestevens**
### Summary of changes

- Update project structure using `pod lib create` to (hopefully) resolve build issues with Carthage.

### Checklist

- ~[ ] Added a changelog entry~

- @scannillo 
- @sestevens

### CODE REVIEW

**Comment by billwerges** [comment]
I know this is the project structure generated by modern CocaoPods, but there are way too many compromises here for us to even consider using it. 

- Having the `xcworkspace` file buried under the Examples directory doesn't make sense.
- The Pods themselves being checked into git isn't great. 
- As far as I can tell the, only way to access the framework classes is to dig into the `Development Pods` group of the Pods project. Since the entire point of this project is to be able to work on the framework itself, having those files buried like that is less than ideal. 
- There are also potential issues with using `@import` and projects that don't have modules enabled. See: https://github.com/braintree/braintree_ios/issues/124

I'm all for trying a different setup for this project, but I don't think following the CocoaPods convention is the way to go. If anything I'd say we should try getting rid of CocoaPods for this project, and try Carthage or a manual integration with Git submodules as a stopgap until we can use Swift Package Manager.

**Comment by sestevens** [comment]
I agree with @billwerges's concerns. I don't like this new structure either. Honestly, we just sunk a lot of time into getting Carthage builds to work, and this is the only solution we came up with.

I'm up for trying a demo app that uses Carthage instead of CocoaPods, though.

**Comment by scannillo** [comment]
@billwerges's points are all valid. This project structure isn't the most intuitive to develop in. Unfortunately, we did spend almost 2 full weeks on getting something to both compile for both Carthage and a demo app using CocoaPods.

Path forward idea **A:**
1) Let's test if this project structure works in a sample App that does not have modules enabled.
2) _If so_, we can continue to develop in this structure temporarily so that pilot merchants can integrate via Carthage or CocoaPods.
3) Then when time permits, trying to restructure the project to use demo app using Carthage instead of CocoaPods.

**B:**
Though, since we don't have pilot merchants knocking at our door, we could hold off on being able to support Carthage right now, and take another stab at the restructure at some point in the future.

Thoughts?

**Comment by scannillo** [comment]
I am leaning toward merging this PR (**option A**), then completing some dev work required to keep the project moving forward. In the meantime, will look into restructuring again using Carthage instead.

**Comment by sestevens** [comment]
I don't have strong opinions, but if our ultimate goal is to keep a structure similar to what we have now, it might be worth going with Option B so that we don't have to go through this process again to get our code _back_ to the original structure.

**Comment by scannillo** [comment]
Thanks for weighing in @sestevens. From chat IRL, @billwerges also prefers option B. 

So - we will shelf this PR for now.

**Comment by scannillo** [comment]
Closing this PR. @billwerges's [commit](https://github.com/braintree/paypal-commerce-platform-ios/commit/d70f5b171069bf71b611fc3ebe397c067b7a0751) resolves the Carthage build issue using our original repo structure 🎉.

The main fix was turning off frameworks for the demo app & adding missing entries to bridging headers.

**Pull request closed without merging**
